### PR TITLE
Fix `Package::readme()` to return correct path

### LINKED ISSUE #201: `Package::readme()` is broken
`Package::readme()` returns invalid path like `/path/to/package/Cargo.toml/README.md`.

https://github.com/oli-obk/cargo_metadata/blob/ea73f56dd64c381574c5b670022d602e43205af5/src/lib.rs#L365-L382

The `readme` path from the TOML file must be combined with `manifest_path.parent().unwrap()`, not `manifest_path`.

### PR DESCRIPTION
**Pull request by gifnksm**
fixes #201

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -375,9 +375,12 @@ impl Package {
 
     /// Full path to the readme file if one is present in the manifest
     pub fn readme(&self) -> Option<Utf8PathBuf> {
-        self.readme
-            .as_ref()
-            .map(|file| self.manifest_path.join(file))
+        self.readme.as_ref().map(|file| {
+            self.manifest_path
+                .parent()
+                .unwrap_or(&self.manifest_path)
```
Comment (jyn514) [inline src/lib.rs:381]: why this `unwrap_or`? shouldn't we return `None` if the manifest path is `/`? not sure how that would happen but still ...

**Review by jyn514 — APPROVED** [review]

File: src/lib.rs (hunk 1 above)
Comment (gifnksm) [reply src/lib.rs:381]: I'm borrowing the implementation from `Package::license()`, so I don't know why unwrap_or is used...

https://github.com/oli-obk/cargo_metadata/blob/ea73f56dd64c381574c5b670022d602e43205af5/src/lib.rs#L367-L374

I will modify `Package::license()` and `Package::readme()` to use `unwrap` instead of `unwrap_or` if you like.

Comment (jyn514) [reply src/lib.rs:381]: > I'm borrowing the implementation from `Package::license()`, so I don't know why `unwrap_or` is used...

ah ok, it's fine to keep it as-is then :) thanks for clarifying!

**Review by jyn514 — APPROVED** [review]
